### PR TITLE
Freeze public available constants. Added tests

### PR DESCRIPTION
**Pull request by luispcosta**
Can we please freeze all public constants?
I've had several errors in my code when using this gem. 

Btw, great work with this gem, it's been really useful to me! I just have this small "problem" with it.

Don't know if there's anything else need for this PR. Let me know if so.

### CODE REVIEW

**Comment by scsmith** [comment]
I'll have a look why the specs aren't passing but in theory I think we should merge this. I guess we might have to bump the version number in case anyone is currently modifying the list in their own code. Any thoughts on this? I don't suspect it is really a breaking change for most people so I think 1.2 will be ok?

**Comment by luispcosta** [comment]
Fine by me to bump the version number 👍

**Comment by scsmith** [comment]
@luispcosta would you mind updating your branch to the current master? It will need the additional constants (for ISO_639_2B and ISO_639_2T) to be frozen as well. However, with master merged and that done it should pass the tests. I'll then merge and get a new build released. I'm also happy to do this if needed but I figure it's easier for you to do as you're already most of the way done.

**Comment by luispcosta** [comment]
@scsmith Just did it !

**Comment by scsmith** [comment]
Thanks, I added one slight change to handle ruby 1.8.7 too but it's now merged, I'll bump and release  as soon as I get a few minutes.

**Pull request merged**
